services:
  agent:
    image: gocd/gocd-agent-wolfi:v24.2.0
    depends_on:
      - server
    environment:
      GO_SERVER_URL: http://server:8153/go
      AGENT_AUTO_REGISTER_KEY: 079e578b-87cc-46c9-9ab5-88997fc7ac59
      GIT_TRACE: 1
      GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
    restart: on-failure
    volumes:
      - ~/.ssh:/home/go/.ssh

  server:
    image: gocd/gocd-server:v24.2.0
    environment:
      GOCD_PLUGIN_INSTALL_script-executor-task:
        https://github.com/gocd-contrib/script-executor-task/releases/download/v1.0.3-213/script-executor-1.0.3-213.jar
      GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
    ports:
      - 8153:8153
    volumes:
      - ~/.ssh:/home/go/.ssh
      - ./build/libs/gocd-git-path-material-plugin-${PLUGIN_VERSION}.jar:/gocd-git-path-material-plugin-${PLUGIN_VERSION}.jar
      - ./extras/config.xml:/config.xml
      - ./extras/server-extra-entrypoint.sh:/docker-entrypoint.d/server-extra-entrypoint.sh
